version: 2

project_name: fray

builds:
  - id: fray
    main: ./cmd/fray
    binary: fray
    ldflags:
      - -s -w
      - -X github.com/adamavenir/fray/internal/command.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
  - id: fray-mcp
    main: ./cmd/fray-mcp
    binary: fray-mcp
    ldflags:
      - -s -w
      - -X github.com/adamavenir/fray/cmd/fray-mcp.Version={{ .Version }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "fray_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    builds:
      - fray
      - fray-mcp
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

brews:
  - name: fray
    directory: Formula
    repository:
      owner: adamavenir
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://fray.so"
    description: "Multi-agent work that flows without losing the thread."
    license: "MIT"
    install: |
      bin.install "fray"
      bin.install "fray-mcp"
