/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/adamavenir/fray/cmd/libfray */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* FrayDiscoverProject(char* startDir);
extern unsigned long long FrayOpenDatabase(char* projectPath);
extern void FrayCloseDatabase(unsigned long long handle);
extern char* FrayGetMessages(unsigned long long handle, char* home, int limit, char* sinceCursor);
extern char* FrayPostMessage(unsigned long long handle, char* body, char* fromAgent, char* home, char* replyTo);
extern char* FrayEditMessage(unsigned long long handle, char* msgID, char* newBody, char* reason);
extern char* FrayAddReaction(unsigned long long handle, char* msgID, char* emoji, char* agent);
extern char* FrayGetAgents(unsigned long long handle, int managedOnly);
extern char* FrayGetAgent(unsigned long long handle, char* agentID);
extern char* FrayGetThreads(unsigned long long handle, char* parentThread, int includeArchived);
extern char* FrayGetThread(unsigned long long handle, char* threadRef);
extern char* FrayGetThreadMessages(unsigned long long handle, char* threadGUID, int limit, char* sinceCursor);
extern char* FraySubscribeToThread(unsigned long long handle, char* threadGUID, char* agentID);
extern char* FrayFaveItem(unsigned long long handle, char* itemGUID, char* agentID);
extern char* FrayGetReadTo(unsigned long long handle, char* agentID, char* home);
extern char* FraySetReadTo(unsigned long long handle, char* agentID, char* home, char* msgID);
extern char* FrayRegisterAgent(unsigned long long handle, char* agentID);
extern char* FrayGetConfig(unsigned long long handle, char* key);
extern char* FraySetConfig(unsigned long long handle, char* key, char* value);
extern char* FrayListChannels(void);
extern char* FrayGetFaves(unsigned long long handle, char* agentID, char* itemType);
extern char* FrayUnfaveItem(unsigned long long handle, char* itemGUID, char* agentID);
extern char* FrayGetAgentUsage(unsigned long long handle, char* agentID);
extern void FrayFreeString(char* ptr);

#ifdef __cplusplus
}
#endif
